import { defineTheme, type DefinedTheme, type TokenValue } from '@astryxdesign/core/theme';
import { dracula } from '@astryxdesign/core/theme/syntax';
import { neutralTheme } from '@astryxdesign/theme-neutral/built';

// Astryx Styles — pure Dracula theme for `<Theme theme mode>`.
// Dark-only: Dracula is a dark spec, so both tuple slots pin the same hex
// and light-dark() resolves identically in either mode.
// Mapping mirrors glimpse glanceColorVars: Dracula accents onto valid Astryx
// tokens, plus glance --color-* vars for widget CSS compat.
// Component overrides ported verbatim from glimpse buildGlimpseTheme.

const DRA = {
  bg: '#282A36',
  fg: '#F8F8F2',
  comment: '#6272A4',
  cyan: '#8BE9FD',
  green: '#50FA7B',
  orange: '#FFB86C',
  pink: '#FF79C6',
  purple: '#BD93F9',
  red: '#FF5555',
  yellow: '#F1FA8C',
} as const;

const pin = (hex: string): [string, string] => [hex, hex];

const tokens: Record<string, TokenValue> = {
  // Dims (glimpse DIMS, frozen)
  '--space-gap': '23px',
  '--space-viewport': '15px',
  '--widget-content-vertical': '15px',
  '--widget-content-horizontal': '17px',
  '--widget-gap': '23px',
  '--tile-row': '96px',
  '--border-radius': '5px',
  '--font-size-h1': '17px',
  '--font-size-h2': '16px',
  '--font-size-h3': '15px',
  '--font-size-h4': '14px',
  '--font-size-base': '13px',
  '--font-size-h5': '12px',
  '--font-size-h6': '11px',
  // Astryx surfaces
  '--color-background-body': pin(DRA.bg),
  '--color-background-surface': pin('#2A2C39'),
  '--color-background-card': pin('#2A2C39'),
  '--color-background-popover': pin('#2D3040'),
  '--color-background-muted': pin('#313342'),
  '--color-overlay-hover': pin('#313342'),
  '--color-overlay-pressed': pin('#313342'),
  '--color-border': pin('#313342'),
  '--color-border-emphasized': pin('#424559'),
  // Astryx semantics from Dracula accents
  '--color-accent': pin(DRA.purple),
  '--color-accent-muted': pin(DRA.cyan),
  '--color-success': pin(DRA.green),
  '--color-error': pin(DRA.red),
  '--color-warning': pin(DRA.yellow),
  '--color-info': pin(DRA.cyan),
  '--color-text-primary': pin('#D3D5DE'),
  '--color-text-secondary': pin('#8489A4'),
  '--color-text-disabled': pin(DRA.comment),
  '--color-text-accent': pin(DRA.purple),
  '--color-icon-primary': pin('#D3D5DE'),
  '--color-icon-secondary': pin('#8489A4'),
  '--color-icon-disabled': pin(DRA.comment),
  '--color-icon-accent': pin(DRA.purple),
  '--color-on-accent': pin('#FFFFFF'),
  '--color-on-success': pin('#000000'),
  '--color-on-warning': pin('#000000'),
  '--color-on-error': pin('#FFFFFF'),
  '--color-track': pin('#313342'),
  '--color-skeleton': pin('#313342'),
  // Charts: categorical series in nearest Dracula hues (teal/brown/indigo have
  // no spectral match, so they reuse cyan/orange/purple)
  '--color-data-categorical-blue': pin(DRA.comment),
  '--color-data-categorical-orange': pin(DRA.orange),
  '--color-data-categorical-purple': pin(DRA.purple),
  '--color-data-categorical-green': pin(DRA.green),
  '--color-data-categorical-pink': pin(DRA.pink),
  '--color-data-categorical-cyan': pin(DRA.cyan),
  '--color-data-categorical-red': pin(DRA.red),
  '--color-data-categorical-teal': pin(DRA.cyan),
  '--color-data-categorical-brown': pin(DRA.orange),
  '--color-data-categorical-indigo': pin(DRA.purple),
  // Sequential ramps from scripts/generate-chart-ramps.ts: constant hue/sat
  // per Dracula family, lightness 28/44/60/74/88 for dark-bg distinctness
  '--color-data-purple-5': pin('hsl(264.71 89.47% 28%)'),
  '--color-data-purple-4': pin('hsl(264.71 89.47% 44%)'),
  '--color-data-purple-3': pin('hsl(264.71 89.47% 60%)'),
  '--color-data-purple-2': pin('hsl(264.71 89.47% 74%)'),
  '--color-data-purple-1': pin('hsl(264.71 89.47% 88%)'),
  '--color-data-pink-5': pin('hsl(325.52 100% 28%)'),
  '--color-data-pink-4': pin('hsl(325.52 100% 44%)'),
  '--color-data-pink-3': pin('hsl(325.52 100% 60%)'),
  '--color-data-pink-2': pin('hsl(325.52 100% 74%)'),
  '--color-data-pink-1': pin('hsl(325.52 100% 88%)'),
  '--color-data-red-5': pin('hsl(0 100% 28%)'),
  '--color-data-red-4': pin('hsl(0 100% 44%)'),
  '--color-data-red-3': pin('hsl(0 100% 60%)'),
  '--color-data-red-2': pin('hsl(0 100% 74%)'),
  '--color-data-red-1': pin('hsl(0 100% 88%)'),
  '--color-data-orange-5': pin('hsl(31.02 100% 28%)'),
  '--color-data-orange-4': pin('hsl(31.02 100% 44%)'),
  '--color-data-orange-3': pin('hsl(31.02 100% 60%)'),
  '--color-data-orange-2': pin('hsl(31.02 100% 74%)'),
  '--color-data-orange-1': pin('hsl(31.02 100% 88%)'),
  '--color-data-yellow-5': pin('hsl(64.91 91.67% 28%)'),
  '--color-data-yellow-4': pin('hsl(64.91 91.67% 44%)'),
  '--color-data-yellow-3': pin('hsl(64.91 91.67% 60%)'),
  '--color-data-yellow-2': pin('hsl(64.91 91.67% 74%)'),
  '--color-data-yellow-1': pin('hsl(64.91 91.67% 88%)'),
  '--color-data-teal-5': pin('hsl(190.53 96.61% 28%)'),
  '--color-data-teal-4': pin('hsl(190.53 96.61% 44%)'),
  '--color-data-teal-3': pin('hsl(190.53 96.61% 60%)'),
  '--color-data-teal-2': pin('hsl(190.53 96.61% 74%)'),
  '--color-data-teal-1': pin('hsl(190.53 96.61% 88%)'),
  '--color-data-blue-5': pin('hsl(225.45 26.61% 28%)'),
  '--color-data-blue-4': pin('hsl(225.45 26.61% 44%)'),
  '--color-data-blue-3': pin('hsl(225.45 26.61% 60%)'),
  '--color-data-blue-2': pin('hsl(225.45 26.61% 74%)'),
  '--color-data-blue-1': pin('hsl(225.45 26.61% 88%)'),
  '--color-data-shamrock-5': pin('hsl(135.18 94.44% 28%)'),
  '--color-data-shamrock-4': pin('hsl(135.18 94.44% 44%)'),
  '--color-data-shamrock-3': pin('hsl(135.18 94.44% 60%)'),
  '--color-data-shamrock-2': pin('hsl(135.18 94.44% 74%)'),
  '--color-data-shamrock-1': pin('hsl(135.18 94.44% 88%)'),
  '--color-data-gray-5': pin('hsl(231.43 14.89% 28%)'),
  '--color-data-gray-4': pin('hsl(231.43 14.89% 44%)'),
  '--color-data-gray-3': pin('hsl(231.43 14.89% 60%)'),
  '--color-data-gray-2': pin('hsl(231.43 14.89% 74%)'),
  '--color-data-gray-1': pin('hsl(231.43 14.89% 88%)'),
  // Glance compat vars (widget CSS reads these directly)
  '--color-background': pin(DRA.bg),
  '--color-widget-background': pin('#2A2C39'),
  '--color-widget-content-border': pin('#313342'),
  '--color-widget-background-highlight': pin('#313342'),
  '--color-separator': pin('#313342'),
  '--color-popover-background': pin('#2D3040'),
  '--color-popover-border': pin('#424559'),
  '--color-progress-border': pin('#3E4153'),
  '--color-progress-value': pin('#606582'),
  '--color-vertical-progress-value': pin('#656A88'),
  '--color-graph-gridlines': pin('#353848'),
  '--color-widget-shadow': pin('#272935'),
  '--color-text-highlight': pin('#D3D5DE'),
  '--color-text-paragraph': pin('#B0B3C4'),
  '--color-text-base': pin('#8489A4'),
  '--color-text-base-muted': pin('#727897'),
  '--color-primary': pin(DRA.purple),
  '--color-positive': pin(DRA.green),
  '--color-negative': pin(DRA.red),
  '--color-tag-orange': pin(DRA.orange),
  '--color-tag-pink': pin(DRA.pink),
  '--color-tag-cyan': pin(DRA.cyan),
  '--color-tag-yellow': pin(DRA.yellow),
  '--color-tag-green': pin(DRA.green),
  '--color-tag-blue': pin(DRA.purple),
  '--color-text-subdue': pin('#4C5067'),
  // Radius: Dracula kit is uniformly 5px
  '--radius-inner': '4px',
  '--radius-element': '5px',
  '--radius-container': '5px',
  '--radius-page': '5px',
};

export const astryxStylesTheme: DefinedTheme = defineTheme({
  name: 'astryx-dracula',
  extends: neutralTheme,
  syntax: dracula,
  tokens,
  typography: {
    scale: { base: 13, ratio: 1.2 },
    body: { family: 'JetBrains Mono', fallbacks: 'monospace' },
    heading: { family: 'JetBrains Mono', fallbacks: 'monospace', weight: 'normal' },
    code: { family: 'JetBrains Mono', fallbacks: 'monospace' },
  },
  components: {
    link: {
      base: {
        color: 'inherit',
        textDecoration: 'none',
        ':hover': { color: 'var(--color-text-highlight)' },
      },
    },
    card: {
      base: {
        backgroundColor: 'var(--color-widget-background)',
        border: '1px solid var(--color-widget-content-border)',
        borderRadius: 'var(--border-radius)',
      },
    },
    button: {
      base: {
        borderRadius: 'var(--border-radius)',
        fontWeight: 'var(--font-weight-normal)',
      },
    },
  },
});
