import { defineTheme, defineSyntaxTheme, type DefinedTheme, type TokenValue } from '@astryxdesign/core/theme';
import { stoneTheme } from '@astryxdesign/theme-stone/built';

// Astryx Styles — pure Dracula theme for `<Theme theme mode>`.
// Dark-only: Dracula Classic is a dark spec, so both tuple slots pin the same
// value and light-dark() resolves identically in either mode.
//
// Base is Stone (spacing, shadows, motion, radii, inputs, icons); this file
// carries only Dracula color authority plus JetBrains Mono, per
// https://raw.githubusercontent.com/dracula/draculatheme.com/refs/heads/main/content/spec.mdx
// Key spec readings: Current Line #6272A4 doubles as the subtle-border color,
// Selection #44475A is the quiet surface, UI surfaces come from the spec UI
// palette, state indicators use Functional colors, text meets WCAG AA
// (verified by scripts/check-contrast.ts).

const DRA = {
  bg: '#282A36',
  fg: '#F8F8F2',
  comment: '#6272A4',
  cyan: '#8BE9FD',
  green: '#50FA7B',
  orange: '#FFB86C',
  pink: '#FF79C6',
  purple: '#BD93F9',
  red: '#FF5555',
  yellow: '#F1FA8C',
} as const;

const pin = (hex: string): [string, string] => [hex, hex];

const draculaSyntax = defineSyntaxTheme({
  name: 'astryx-dracula',
  tokens: {
    keyword: DRA.pink,
    string: DRA.yellow,
    comment: DRA.comment,
    number: DRA.orange,
    function: DRA.green,
    type: DRA.cyan,
    variable: DRA.fg,
    operator: DRA.pink,
    constant: DRA.orange,
    tag: DRA.pink,
    attribute: DRA.yellow,
    property: DRA.cyan,
    punctuation: DRA.fg,
    background: DRA.bg,
  },
});

const tokens: Record<string, TokenValue> = {
  // Compat dims (glance widget CSS; no Astryx collision)
  '--space-gap': '23px',
  '--space-viewport': '15px',
  '--widget-content-vertical': '15px',
  '--widget-content-horizontal': '17px',
  '--widget-gap': '23px',
  '--tile-row': '96px',
  '--border-radius': '5px',
  // Astryx surfaces from the spec UI palette
  '--color-background-body': pin(DRA.bg),
  '--color-background-surface': pin('#343746'),
  '--color-background-card': pin('#343746'),
  '--color-background-popover': pin('#424450'),
  '--color-background-muted': pin('#44475A'),
  '--color-overlay-hover': pin('#353747'),
  '--color-overlay-pressed': pin('#44475A'),
  '--color-border': pin('#44475A'),
  '--color-border-emphasized': pin(DRA.comment),
  // Astryx semantics from Dracula accents (text roles AA-verified)
  '--color-accent': pin(DRA.purple),
  '--color-accent-muted': pin(DRA.cyan),
  '--color-success': pin(DRA.green),
  '--color-error': pin(DRA.red),
  '--color-warning': pin(DRA.yellow),
  '--color-info': pin(DRA.cyan),
  '--color-text-primary': pin(DRA.fg),
  '--color-text-secondary': pin('#9AA1BC'),
  '--color-text-disabled': pin(DRA.comment),
  '--color-text-accent': pin(DRA.purple),
  '--color-icon-primary': pin(DRA.fg),
  '--color-icon-secondary': pin('#9AA1BC'),
  '--color-icon-disabled': pin(DRA.comment),
  '--color-icon-accent': pin(DRA.purple),
  '--color-on-accent': pin('#000000'),
  '--color-on-success': pin('#000000'),
  '--color-on-warning': pin('#000000'),
  '--color-on-error': pin('#FFFFFF'),
  '--color-on-info': pin('#000000'),
  '--color-track': pin('#44475A'),
  '--color-skeleton': pin('#44475A'),
  // Spec functional colors for fills, interactive borders, focus
  '--color-functional-red': pin('#DE5735'),
  '--color-functional-orange': pin('#A39514'),
  '--color-functional-green': pin('#089108'),
  '--color-functional-cyan': pin('#0081D6'),
  '--color-functional-purple': pin('#815CD6'),
  // Charts: categorical series in nearest Dracula hues (ANSI brights keep
  // teal/indigo distinct; brown reuses orange, its closest hue)
  '--color-data-categorical-blue': pin(DRA.comment),
  '--color-data-categorical-orange': pin(DRA.orange),
  '--color-data-categorical-purple': pin(DRA.purple),
  '--color-data-categorical-green': pin(DRA.green),
  '--color-data-categorical-pink': pin(DRA.pink),
  '--color-data-categorical-cyan': pin(DRA.cyan),
  '--color-data-categorical-red': pin(DRA.red),
  '--color-data-categorical-teal': pin('#A4FFFF'),
  '--color-data-categorical-brown': pin(DRA.orange),
  '--color-data-categorical-indigo': pin('#D6ACFF'),
  // Sequential ramps from scripts/generate-chart-ramps.ts: constant hue/sat
  // per Dracula family, lightness 28/44/60/74/88 for dark-bg distinctness
  '--color-data-purple-5': pin('hsl(264.71 89.47% 28%)'),
  '--color-data-purple-4': pin('hsl(264.71 89.47% 44%)'),
  '--color-data-purple-3': pin('hsl(264.71 89.47% 60%)'),
  '--color-data-purple-2': pin('hsl(264.71 89.47% 74%)'),
  '--color-data-purple-1': pin('hsl(264.71 89.47% 88%)'),
  '--color-data-pink-5': pin('hsl(325.52 100% 28%)'),
  '--color-data-pink-4': pin('hsl(325.52 100% 44%)'),
  '--color-data-pink-3': pin('hsl(325.52 100% 60%)'),
  '--color-data-pink-2': pin('hsl(325.52 100% 74%)'),
  '--color-data-pink-1': pin('hsl(325.52 100% 88%)'),
  '--color-data-red-5': pin('hsl(0 100% 28%)'),
  '--color-data-red-4': pin('hsl(0 100% 44%)'),
  '--color-data-red-3': pin('hsl(0 100% 60%)'),
  '--color-data-red-2': pin('hsl(0 100% 74%)'),
  '--color-data-red-1': pin('hsl(0 100% 88%)'),
  '--color-data-orange-5': pin('hsl(31.02 100% 28%)'),
  '--color-data-orange-4': pin('hsl(31.02 100% 44%)'),
  '--color-data-orange-3': pin('hsl(31.02 100% 60%)'),
  '--color-data-orange-2': pin('hsl(31.02 100% 74%)'),
  '--color-data-orange-1': pin('hsl(31.02 100% 88%)'),
  '--color-data-yellow-5': pin('hsl(64.91 91.67% 28%)'),
  '--color-data-yellow-4': pin('hsl(64.91 91.67% 44%)'),
  '--color-data-yellow-3': pin('hsl(64.91 91.67% 60%)'),
  '--color-data-yellow-2': pin('hsl(64.91 91.67% 74%)'),
  '--color-data-yellow-1': pin('hsl(64.91 91.67% 88%)'),
  '--color-data-teal-5': pin('hsl(190.53 96.61% 28%)'),
  '--color-data-teal-4': pin('hsl(190.53 96.61% 44%)'),
  '--color-data-teal-3': pin('hsl(190.53 96.61% 60%)'),
  '--color-data-teal-2': pin('hsl(190.53 96.61% 74%)'),
  '--color-data-teal-1': pin('hsl(190.53 96.61% 88%)'),
  '--color-data-blue-5': pin('hsl(225.45 26.61% 28%)'),
  '--color-data-blue-4': pin('hsl(225.45 26.61% 44%)'),
  '--color-data-blue-3': pin('hsl(225.45 26.61% 60%)'),
  '--color-data-blue-2': pin('hsl(225.45 26.61% 74%)'),
  '--color-data-blue-1': pin('hsl(225.45 26.61% 88%)'),
  '--color-data-shamrock-5': pin('hsl(135.18 94.44% 28%)'),
  '--color-data-shamrock-4': pin('hsl(135.18 94.44% 44%)'),
  '--color-data-shamrock-3': pin('hsl(135.18 94.44% 60%)'),
  '--color-data-shamrock-2': pin('hsl(135.18 94.44% 74%)'),
  '--color-data-shamrock-1': pin('hsl(135.18 94.44% 88%)'),
  '--color-data-gray-5': pin('hsl(231.43 14.89% 28%)'),
  '--color-data-gray-4': pin('hsl(231.43 14.89% 44%)'),
  '--color-data-gray-3': pin('hsl(231.43 14.89% 60%)'),
  '--color-data-gray-2': pin('hsl(231.43 14.89% 74%)'),
  '--color-data-gray-1': pin('hsl(231.43 14.89% 88%)'),
  // Glance compat vars (widget CSS reads these directly)
  '--color-background': pin(DRA.bg),
  '--color-widget-background': pin('#343746'),
  '--color-widget-content-border': pin('#44475A'),
  '--color-widget-background-highlight': pin('#44475A'),
  '--color-separator': pin('#44475A'),
  '--color-popover-background': pin('#424450'),
  '--color-popover-border': pin(DRA.comment),
  '--color-progress-border': pin('#44475A'),
  '--color-progress-value': pin(DRA.comment),
  '--color-vertical-progress-value': pin(DRA.comment),
  '--color-graph-gridlines': pin('#44475A'),
  '--color-widget-shadow': pin('#21222C'),
  '--color-text-highlight': pin(DRA.fg),
  '--color-text-paragraph': pin('#B0B3C4'),
  '--color-text-base': pin('#9AA1BC'),
  '--color-text-base-muted': pin('#8288A6'),
  '--color-text-subdue': pin('#4C5067'),
  '--color-current-line': pin(DRA.comment),
  '--color-selection': pin('#44475A'),
  '--color-primary': pin(DRA.purple),
  '--color-positive': pin(DRA.green),
  '--color-negative': pin(DRA.red),
  '--color-tag-orange': pin(DRA.orange),
  '--color-tag-pink': pin(DRA.pink),
  '--color-tag-cyan': pin(DRA.cyan),
  '--color-tag-yellow': pin(DRA.yellow),
  '--color-tag-green': pin(DRA.green),
  '--color-tag-blue': pin(DRA.purple),
};

export const astryxStylesTheme: DefinedTheme = defineTheme({
  name: 'astryx-dracula',
  extends: stoneTheme,
  syntax: draculaSyntax,
  tokens,
  typography: {
    scale: { base: 14, ratio: 1.25 },
    body: { family: 'JetBrains Mono', fallbacks: 'monospace' },
    heading: { family: 'JetBrains Mono', fallbacks: 'monospace', weight: 'normal', weights: { 3: 'bold', 4: 'bold' } },
    code: { family: 'JetBrains Mono', fallbacks: 'monospace' },
  },
});
