/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: astryx-theme.ts
 * Command: astryx theme build astryx-theme.ts --out theme.css
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/ProgressBar' {
  interface ProgressBarVariantMap {
    'accent': true;
    'success': true;
    'warning': true;
    'error': true;
  }
}
