/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: astryx-theme.ts
 * Command: astryx theme build astryx-theme.ts --out theme.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/StatusDot' {
  interface StatusDotVariantMap {
    'info': true;
  }
}

declare module '@astryxdesign/core/ProgressBar' {
  interface ProgressBarVariantMap {
    'disabled': true;
  }
}
