import { defineTheme, defineSyntaxTheme, type DefinedTheme, type TokenValue } from '@astryxdesign/core/theme';
import { draculaIconRegistry } from './icons';

// Astryx Styles — pure Dracula theme for `<Theme theme mode>`.
// Dark-only: Dracula Classic is a dark spec, so both tuple slots pin the same
// value and light-dark() resolves identically in either mode.
//
// Base is Stone (spacing, shadows, motion, radii, inputs, icons); this file
// carries only Dracula color authority plus JetBrains Mono, per
// https://raw.githubusercontent.com/dracula/draculatheme.com/refs/heads/main/content/spec.mdx
// Key spec readings: Current Line #6272A4 doubles as the subtle-border color,
// Selection #44475A is the quiet surface, UI surfaces come from the spec UI
// palette, state indicators use Functional colors, text meets WCAG AA
// (verified by scripts/check.ts).

const DRA = {
  bg: '#282A36',
  fg: '#F8F8F2',
  comment: '#6272A4',
  cyan: '#8BE9FD',
  green: '#50FA7B',
  orange: '#FFB86C',
  pink: '#FF79C6',
  purple: '#BD93F9',
  red: '#FF5555',
  yellow: '#F1FA8C',
} as const;

const pin = (hex: string): [string, string] => [hex, hex];

const draculaSyntax = defineSyntaxTheme({
  name: 'astryx-dracula',
  tokens: {
    keyword: DRA.pink,
    string: DRA.yellow,
    comment: DRA.comment,
    number: DRA.orange,
    function: DRA.green,
    type: DRA.cyan,
    variable: DRA.fg,
    operator: DRA.pink,
    constant: DRA.orange,
    tag: DRA.pink,
    attribute: DRA.yellow,
    property: DRA.cyan,
    punctuation: DRA.fg,
    background: DRA.bg,
  },
});

const tokens: Record<string, TokenValue> = {
  // Compat dims (glance widget CSS; no Astryx collision)
  '--radius-inner': '4px',
  '--radius-element': '5px',
  '--radius-container': '5px',
  '--radius-page': '5px',
  '--font-size-h1': '17px',
  '--font-size-h2': '16px',
  '--font-size-h3': '15px',
  '--font-size-h4': '14px',
  '--font-size-base': '13px',
  '--font-size-h5': '12px',
  '--font-size-h6': '11px',
  '--shadow-low': '0 2px 4px #191A210D, 0 4px 8px #191A211A',
  '--shadow-med': '0 2px 4px #191A210D, 0 4px 12px #191A211A',
  '--shadow-high': '0 4px 6px #191A211A, 0 12px 24px #191A2126',
  '--shadow-inset-hover': 'inset 0px 0px 0px 2px #6272A430',
  '--shadow-inset-success': 'inset 0px 0px 0px 2px #50FA7B30',
  '--shadow-inset-warning': 'inset 0px 0px 0px 2px #F1FA8C30',
  '--shadow-inset-error': 'inset 0px 0px 0px 2px #FF555530',
  '--color-neutral': pin('#F8F8F21A'),
  '--color-background-inverted': pin('#F8F8F2'),
  '--color-background-error-inverted': pin('#FFD5CC'),
  '--color-accent-muted': 'var(--color-background-purple)',
  '--color-success-muted': 'var(--color-background-green)',
  '--color-warning-muted': 'var(--color-background-yellow)',
  '--color-error-muted': 'var(--color-background-red)',
  '--color-info-muted': 'var(--color-background-cyan)',
  '--space-gap': '23px',
  '--space-viewport': '15px',
  '--widget-content-vertical': '15px',
  '--widget-content-horizontal': '17px',
  '--widget-gap': '23px',
  '--tile-row': '96px',
  '--border-radius': '5px',
  // Astryx surfaces from the spec UI palette
  '--color-background-body': pin(DRA.bg),
  '--color-background-surface': pin('#343746'),
  '--color-background-card': pin('#343746'),
  '--color-background-popover': pin('#424450'),
  '--color-background-muted': pin('#44475A'),
  '--color-overlay': pin('#191A21CC'),
  '--color-overlay-hover': pin('#0000001F'),
  '--color-overlay-pressed': pin('#00000033'),
  '--color-border': pin(DRA.comment),
  '--color-border-emphasized': pin(DRA.comment),
  // Astryx semantics from Dracula accents (text roles AA-verified)
  '--color-accent': pin(DRA.purple),
  '--color-success': pin(DRA.green),
  '--color-error': pin(DRA.red),
  '--color-warning': pin(DRA.yellow),
  '--color-info': pin(DRA.cyan),
  '--color-text-primary': pin(DRA.fg),
  '--color-text-secondary': pin('#9AA1BC'),
  '--color-text-disabled': pin(DRA.comment),
  '--color-text-accent': pin(DRA.purple),
  '--color-icon-primary': pin(DRA.fg),
  '--color-icon-secondary': pin('#9AA1BC'),
  '--color-icon-disabled': pin(DRA.comment),
  '--color-icon-accent': pin(DRA.purple),
  '--color-on-accent': pin('#21222C'),
  '--color-on-success': pin('#21222C'),
  '--color-on-warning': pin('#21222C'),
  '--color-on-error': pin('#21222C'),
  '--color-on-info': pin('#21222C'),
  '--color-track': pin(DRA.comment),
  '--color-skeleton': pin(DRA.comment),
  // Spec functional colors for fills, interactive borders, focus
  '--color-functional-red': pin('#DE5735'),
  '--color-functional-orange': pin('#A39514'),
  '--color-functional-green': pin('#089108'),
  '--color-functional-cyan': pin('#0081D6'),
  '--color-functional-purple': pin('#815CD6'),
  // Charts: categorical series in nearest Dracula hues (ANSI brights keep
  // teal/indigo distinct; brown reuses orange, its closest hue)
  '--color-data-categorical-blue': pin(DRA.comment),
  '--color-data-categorical-orange': pin(DRA.orange),
  '--color-data-categorical-purple': pin(DRA.purple),
  '--color-data-categorical-green': pin(DRA.green),
  '--color-data-categorical-pink': pin(DRA.pink),
  '--color-data-categorical-cyan': pin(DRA.cyan),
  '--color-data-categorical-red': pin(DRA.red),
  '--color-data-categorical-teal': pin('#A4FFFF'),
  '--color-data-categorical-brown': pin(DRA.orange),
  '--color-data-categorical-indigo': pin('#D6ACFF'),
  // Categorical tints: 10% accent wash backgrounds, 30% borders, full accents
  // for text and icons. Stone badge, banner, and field-status scopes resolve
  // these, so all status surfaces follow Dracula with zero per-scope hacks.
  '--color-background-blue': pin('#6272A41A'),
  '--color-border-blue': pin('#6272A44D'),
  '--color-icon-blue': pin(DRA.comment),
  '--color-text-blue': pin(DRA.comment),
  '--color-background-cyan': pin('#8BE9FD1A'),
  '--color-border-cyan': pin('#8BE9FD4D'),
  '--color-icon-cyan': pin(DRA.cyan),
  '--color-text-cyan': pin(DRA.cyan),
  '--color-background-gray': pin('#9AA1BC1A'),
  '--color-border-gray': pin('#9AA1BC4D'),
  '--color-icon-gray': pin('#9AA1BC'),
  '--color-text-gray': pin('#9AA1BC'),
  '--color-background-green': pin('#50FA7B1A'),
  '--color-border-green': pin('#50FA7B4D'),
  '--color-icon-green': pin(DRA.green),
  '--color-text-green': pin(DRA.green),
  '--color-background-orange': pin('#FFB86C1A'),
  '--color-border-orange': pin('#FFB86C4D'),
  '--color-icon-orange': pin(DRA.orange),
  '--color-text-orange': pin(DRA.orange),
  '--color-background-pink': pin('#FF79C61A'),
  '--color-border-pink': pin('#FF79C64D'),
  '--color-icon-pink': pin(DRA.pink),
  '--color-text-pink': pin(DRA.pink),
  '--color-background-purple': pin('#BD93F91A'),
  '--color-border-purple': pin('#BD93F94D'),
  '--color-icon-purple': pin(DRA.purple),
  '--color-text-purple': pin(DRA.purple),
  '--color-background-red': pin('#FF55551A'),
  '--color-border-red': pin('#FF55554D'),
  '--color-icon-red': pin(DRA.red),
  '--color-text-red': pin(DRA.red),
  '--color-background-teal': pin('#A4FFFF1A'),
  '--color-border-teal': pin('#A4FFFF4D'),
  '--color-icon-teal': pin('#A4FFFF'),
  '--color-text-teal': pin('#A4FFFF'),
  '--color-background-yellow': pin('#F1FA8C1A'),
  '--color-border-yellow': pin('#F1FA8C4D'),
  '--color-icon-yellow': pin(DRA.yellow),
  '--color-text-yellow': pin(DRA.yellow),
  // Sequential ramps: constant hue/sat per Dracula family, lightness
  // 28/44/60/74/88 for dark-bg distinctness
  '--color-data-purple-5': pin('hsl(264.71 89.47% 28%)'),
  '--color-data-purple-4': pin('hsl(264.71 89.47% 44%)'),
  '--color-data-purple-3': pin('hsl(264.71 89.47% 60%)'),
  '--color-data-purple-2': pin('hsl(264.71 89.47% 74%)'),
  '--color-data-purple-1': pin('hsl(264.71 89.47% 88%)'),
  '--color-data-pink-5': pin('hsl(325.52 100% 28%)'),
  '--color-data-pink-4': pin('hsl(325.52 100% 44%)'),
  '--color-data-pink-3': pin('hsl(325.52 100% 60%)'),
  '--color-data-pink-2': pin('hsl(325.52 100% 74%)'),
  '--color-data-pink-1': pin('hsl(325.52 100% 88%)'),
  '--color-data-red-5': pin('hsl(0 100% 28%)'),
  '--color-data-red-4': pin('hsl(0 100% 44%)'),
  '--color-data-red-3': pin('hsl(0 100% 60%)'),
  '--color-data-red-2': pin('hsl(0 100% 74%)'),
  '--color-data-red-1': pin('hsl(0 100% 88%)'),
  '--color-data-orange-5': pin('hsl(31.02 100% 28%)'),
  '--color-data-orange-4': pin('hsl(31.02 100% 44%)'),
  '--color-data-orange-3': pin('hsl(31.02 100% 60%)'),
  '--color-data-orange-2': pin('hsl(31.02 100% 74%)'),
  '--color-data-orange-1': pin('hsl(31.02 100% 88%)'),
  '--color-data-yellow-5': pin('hsl(64.91 91.67% 28%)'),
  '--color-data-yellow-4': pin('hsl(64.91 91.67% 44%)'),
  '--color-data-yellow-3': pin('hsl(64.91 91.67% 60%)'),
  '--color-data-yellow-2': pin('hsl(64.91 91.67% 74%)'),
  '--color-data-yellow-1': pin('hsl(64.91 91.67% 88%)'),
  '--color-data-teal-5': pin('hsl(190.53 96.61% 28%)'),
  '--color-data-teal-4': pin('hsl(190.53 96.61% 44%)'),
  '--color-data-teal-3': pin('hsl(190.53 96.61% 60%)'),
  '--color-data-teal-2': pin('hsl(190.53 96.61% 74%)'),
  '--color-data-teal-1': pin('hsl(190.53 96.61% 88%)'),
  '--color-data-blue-5': pin('hsl(225.45 26.61% 28%)'),
  '--color-data-blue-4': pin('hsl(225.45 26.61% 44%)'),
  '--color-data-blue-3': pin('hsl(225.45 26.61% 60%)'),
  '--color-data-blue-2': pin('hsl(225.45 26.61% 74%)'),
  '--color-data-blue-1': pin('hsl(225.45 26.61% 88%)'),
  '--color-data-shamrock-5': pin('hsl(135.18 94.44% 28%)'),
  '--color-data-shamrock-4': pin('hsl(135.18 94.44% 44%)'),
  '--color-data-shamrock-3': pin('hsl(135.18 94.44% 60%)'),
  '--color-data-shamrock-2': pin('hsl(135.18 94.44% 74%)'),
  '--color-data-shamrock-1': pin('hsl(135.18 94.44% 88%)'),
  '--color-data-gray-5': pin('hsl(231.43 14.89% 28%)'),
  '--color-data-gray-4': pin('hsl(231.43 14.89% 44%)'),
  '--color-data-gray-3': pin('hsl(231.43 14.89% 60%)'),
  '--color-data-gray-2': pin('hsl(231.43 14.89% 74%)'),
  '--color-data-gray-1': pin('hsl(231.43 14.89% 88%)'),
  // Glance compat vars (widget CSS reads these directly)
  '--color-background': pin(DRA.bg),
  '--color-widget-background': pin('#343746'),
  '--color-widget-content-border': pin(DRA.comment),
  '--color-widget-background-highlight': pin('#44475A'),
  '--color-separator': pin('#44475A'),
  '--color-popover-background': pin('#424450'),
  '--color-popover-border': pin(DRA.comment),
  '--color-progress-border': pin('#44475A'),
  '--color-progress-value': pin(DRA.comment),
  '--color-vertical-progress-value': pin(DRA.comment),
  '--color-graph-gridlines': pin('#44475A'),
  '--color-widget-shadow': pin('#21222C'),
  '--color-text-highlight': pin(DRA.fg),
  '--color-text-paragraph': pin('#B0B3C4'),
  '--color-text-base': pin('#9AA1BC'),
  '--color-text-base-muted': pin('#8288A6'),
  '--color-text-subdue': pin('#4C5067'),
  '--color-current-line': pin(DRA.comment),
  '--color-selection': pin('#44475A'),
  '--color-primary': pin(DRA.purple),
  '--color-positive': pin(DRA.green),
  '--color-negative': pin(DRA.red),
  '--color-tag-orange': pin(DRA.orange),
  '--color-tag-pink': pin(DRA.pink),
  '--color-tag-cyan': pin(DRA.cyan),
  '--color-tag-yellow': pin(DRA.yellow),
  '--color-tag-green': pin(DRA.green),
  '--color-tag-blue': pin(DRA.purple),
};

// Input validation tint shared by all 9 input components (stone shapes it per
// component; one const keeps the nine in lockstep).
const INPUT_STATUS = {
  'status:success': { '--color-success': DRA.green },
  'status:warning': { '--color-warning': DRA.yellow },
  'status:error': { '--color-error': DRA.red },
};

export const astryxDraculaTheme: DefinedTheme = defineTheme({
  name: 'astryx-dracula',
  icons: draculaIconRegistry,
  syntax: draculaSyntax,
  tokens,
  typography: {
    scale: { base: 13, ratio: 1.2 },
    body: { family: 'JetBrains Mono', fallbacks: 'monospace' },
    heading: { family: 'JetBrains Mono', fallbacks: 'monospace', weight: 'normal' },
    code: { family: 'JetBrains Mono', fallbacks: 'monospace' },
  },
  motion: { fast: 175, medium: 410, slow: 975, ratio: 0.75 },
  components: {
    link: {
      base: {
        color: 'var(--color-text-accent)',
        textDecoration: 'underline',
        ':hover': { color: 'var(--color-text-highlight)' },
      },
    },
    card: {
      base: {
        backgroundColor: 'var(--color-widget-background)',
        border: '1px solid var(--color-widget-content-border)',
        borderRadius: 'var(--border-radius)',
      },
    },
    button: {
      base: {
        borderRadius: 'var(--border-radius)',
        fontWeight: 'var(--font-weight-normal)',
      },
    },
    banner: {
      base: {
        borderRadius: 'var(--border-radius)',
        borderWidth: '1px',
        borderStyle: 'solid',
        color: 'var(--color-text-primary)',
      },
      'status:info': {
        '--color-accent-muted': 'var(--color-background-cyan)',
        borderColor: 'var(--color-info)',
      },
      'status:success': {
        '--color-success-muted': 'var(--color-background-green)',
        borderColor: 'var(--color-success)',
      },
      'status:warning': {
        '--color-warning-muted': 'var(--color-background-yellow)',
        borderColor: 'var(--color-warning)',
      },
      'status:error': {
        '--color-error-muted': 'var(--color-background-red)',
        borderColor: 'var(--color-error)',
      },
    },
    'progressbar-fill': {
      'variant:accent': {
        backgroundColor: DRA.purple,
      },
      'variant:success': {
        backgroundColor: DRA.green,
      },
      'variant:warning': {
        backgroundColor: DRA.yellow,
      },
      'variant:error': {
        backgroundColor: DRA.red,
      },
    },
    'text-input': INPUT_STATUS,
    textarea: INPUT_STATUS,
    'number-input': INPUT_STATUS,
    'date-input': INPUT_STATUS,
    'time-input': INPUT_STATUS,
    selector: INPUT_STATUS,
    'multi-selector': INPUT_STATUS,
    typeahead: INPUT_STATUS,
    tokenizer: INPUT_STATUS,
    switch: {
      base: {
        '--color-background-gray': 'var(--color-skeleton)',
      },
    },
    'field-status': {
      'type:success': {
        backgroundColor: 'var(--color-background-green)',
      },
      'type:warning': {
        backgroundColor: 'var(--color-background-yellow)',
      },
      'type:error': {
        backgroundColor: 'var(--color-background-red)',
      },
    },
  },
});
