/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: astryx-theme.ts
 * Command: astryx theme build astryx-theme.ts --out theme.css
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

/// <reference path="./astryx-dracula.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const astryxDraculaTheme: DefinedTheme;
